/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as CursorIndexRouteImport } from './routes/cursor.index'
import { Route as AntigravityIndexRouteImport } from './routes/antigravity.index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'
import { Route as ProjectsProjectRouteImport } from './routes/projects.$project'
import { Route as CursorWorkspaceKeyRouteImport } from './routes/cursor.$workspaceKey'
import { Route as CursorThreadsComposerIdRouteImport } from './routes/cursor-threads.$composerId'
import { Route as AntigravityWorkspaceKeyRouteImport } from './routes/antigravity.$workspaceKey'
import { Route as AntigravityConversationsConversationIdRouteImport } from './routes/antigravity-conversations.$conversationId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorIndexRoute = CursorIndexRouteImport.update({
  id: '/cursor/',
  path: '/cursor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigravityIndexRoute = AntigravityIndexRouteImport.update({
  id: '/antigravity/',
  path: '/antigravity/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorWorkspaceKeyRoute = CursorWorkspaceKeyRouteImport.update({
  id: '/cursor/$workspaceKey',
  path: '/cursor/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorThreadsComposerIdRoute = CursorThreadsComposerIdRouteImport.update({
  id: '/cursor-threads/$composerId',
  path: '/cursor-threads/$composerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigravityWorkspaceKeyRoute = AntigravityWorkspaceKeyRouteImport.update({
  id: '/antigravity/$workspaceKey',
  path: '/antigravity/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigravityConversationsConversationIdRoute =
  AntigravityConversationsConversationIdRouteImport.update({
    id: '/antigravity-conversations/$conversationId',
    path: '/antigravity-conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity/': typeof AntigravityIndexRoute
  '/cursor/': typeof CursorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity': typeof AntigravityIndexRoute
  '/cursor': typeof CursorIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity/': typeof AntigravityIndexRoute
  '/cursor/': typeof CursorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/projects/$project'
    | '/threads/$threadId'
    | '/antigravity/'
    | '/cursor/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/projects/$project'
    | '/threads/$threadId'
    | '/antigravity'
    | '/cursor'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/projects/$project'
    | '/threads/$threadId'
    | '/antigravity/'
    | '/cursor/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  AnalyticsRoute: typeof AnalyticsRoute
  SettingsRoute: typeof SettingsRoute
  AntigravityConversationsConversationIdRoute: typeof AntigravityConversationsConversationIdRoute
  AntigravityWorkspaceKeyRoute: typeof AntigravityWorkspaceKeyRoute
  CursorThreadsComposerIdRoute: typeof CursorThreadsComposerIdRoute
  CursorWorkspaceKeyRoute: typeof CursorWorkspaceKeyRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  AntigravityIndexRoute: typeof AntigravityIndexRoute
  CursorIndexRoute: typeof CursorIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor/': {
      id: '/cursor/'
      path: '/cursor'
      fullPath: '/cursor/'
      preLoaderRoute: typeof CursorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity/': {
      id: '/antigravity/'
      path: '/antigravity'
      fullPath: '/antigravity/'
      preLoaderRoute: typeof AntigravityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor/$workspaceKey': {
      id: '/cursor/$workspaceKey'
      path: '/cursor/$workspaceKey'
      fullPath: '/cursor/$workspaceKey'
      preLoaderRoute: typeof CursorWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor-threads/$composerId': {
      id: '/cursor-threads/$composerId'
      path: '/cursor-threads/$composerId'
      fullPath: '/cursor-threads/$composerId'
      preLoaderRoute: typeof CursorThreadsComposerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity/$workspaceKey': {
      id: '/antigravity/$workspaceKey'
      path: '/antigravity/$workspaceKey'
      fullPath: '/antigravity/$workspaceKey'
      preLoaderRoute: typeof AntigravityWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity-conversations/$conversationId': {
      id: '/antigravity-conversations/$conversationId'
      path: '/antigravity-conversations/$conversationId'
      fullPath: '/antigravity-conversations/$conversationId'
      preLoaderRoute: typeof AntigravityConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  AnalyticsRoute: AnalyticsRoute,
  SettingsRoute: SettingsRoute,
  AntigravityConversationsConversationIdRoute:
    AntigravityConversationsConversationIdRoute,
  AntigravityWorkspaceKeyRoute: AntigravityWorkspaceKeyRoute,
  CursorThreadsComposerIdRoute: CursorThreadsComposerIdRoute,
  CursorWorkspaceKeyRoute: CursorWorkspaceKeyRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  AntigravityIndexRoute: AntigravityIndexRoute,
  CursorIndexRoute: CursorIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
