/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QoderIndexRouteImport } from './routes/qoder.index'
import { Route as OpencodeIndexRouteImport } from './routes/opencode.index'
import { Route as MinimaxCodeIndexRouteImport } from './routes/minimax-code.index'
import { Route as KiroIndexRouteImport } from './routes/kiro.index'
import { Route as GrokIndexRouteImport } from './routes/grok.index'
import { Route as CursorIndexRouteImport } from './routes/cursor.index'
import { Route as CodexIndexRouteImport } from './routes/codex.index'
import { Route as ClaudeCodeIndexRouteImport } from './routes/claude-code.index'
import { Route as AntigravityIndexRouteImport } from './routes/antigravity.index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'
import { Route as QoderWorkspaceKeyRouteImport } from './routes/qoder.$workspaceKey'
import { Route as QoderSessionsSessionIdRouteImport } from './routes/qoder-sessions.$sessionId'
import { Route as OpencodeWorkspaceKeyRouteImport } from './routes/opencode.$workspaceKey'
import { Route as OpencodeSessionsSessionIdRouteImport } from './routes/opencode-sessions.$sessionId'
import { Route as MinimaxCodeWorkspaceKeyRouteImport } from './routes/minimax-code.$workspaceKey'
import { Route as MinimaxCodeSessionsSessionIdRouteImport } from './routes/minimax-code-sessions.$sessionId'
import { Route as KiroWorkspaceKeyRouteImport } from './routes/kiro.$workspaceKey'
import { Route as KiroSessionsSessionIdRouteImport } from './routes/kiro-sessions.$sessionId'
import { Route as GrokWorkspaceKeyRouteImport } from './routes/grok.$workspaceKey'
import { Route as GrokSessionsSessionIdRouteImport } from './routes/grok-sessions.$sessionId'
import { Route as CursorWorkspaceKeyRouteImport } from './routes/cursor.$workspaceKey'
import { Route as CursorThreadsComposerIdRouteImport } from './routes/cursor-threads.$composerId'
import { Route as CodexProjectRouteImport } from './routes/codex.$project'
import { Route as ClaudeCodeWorkspaceKeyRouteImport } from './routes/claude-code.$workspaceKey'
import { Route as ClaudeCodeSessionsSessionIdRouteImport } from './routes/claude-code-sessions.$sessionId'
import { Route as AntigravityWorkspaceKeyRouteImport } from './routes/antigravity.$workspaceKey'
import { Route as AntigravityConversationsConversationIdRouteImport } from './routes/antigravity-conversations.$conversationId'
import { Route as ApiV1SourcesRouteImport } from './routes/api.v1.sources'
import { Route as ApiV1ResolveRouteImport } from './routes/api.v1.resolve'
import { Route as ApiV1ConversationsRouteImport } from './routes/api.v1.conversations'
import { Route as ApiV1ConversationQueryRouteImport } from './routes/api.v1.conversation-query'
import { Route as ApiV1ConversationsExportRouteImport } from './routes/api.v1.conversations.export'
import { Route as ApiV1ConversationsDeleteRouteImport } from './routes/api.v1.conversations.delete'
import { Route as ApiV1ConversationsSourceIdRouteImport } from './routes/api.v1.conversations.$source.$id'
import { Route as ApiV1CodexThreadsEventsRouteImport } from './routes/api.v1.codex.threads.events'
import { Route as ApiV1ConversationsSourceIdExportRouteImport } from './routes/api.v1.conversations.$source.$id.export'
import { Route as ApiV1ConversationsSourceIdEvidenceRouteImport } from './routes/api.v1.conversations.$source.$id.evidence'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QoderIndexRoute = QoderIndexRouteImport.update({
  id: '/qoder/',
  path: '/qoder/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencodeIndexRoute = OpencodeIndexRouteImport.update({
  id: '/opencode/',
  path: '/opencode/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimaxCodeIndexRoute = MinimaxCodeIndexRouteImport.update({
  id: '/minimax-code/',
  path: '/minimax-code/',
  getParentRoute: () => rootRouteImport,
} as any)
const KiroIndexRoute = KiroIndexRouteImport.update({
  id: '/kiro/',
  path: '/kiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokIndexRoute = GrokIndexRouteImport.update({
  id: '/grok/',
  path: '/grok/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorIndexRoute = CursorIndexRouteImport.update({
  id: '/cursor/',
  path: '/cursor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexIndexRoute = CodexIndexRouteImport.update({
  id: '/codex/',
  path: '/codex/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeIndexRoute = ClaudeCodeIndexRouteImport.update({
  id: '/claude-code/',
  path: '/claude-code/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigravityIndexRoute = AntigravityIndexRouteImport.update({
  id: '/antigravity/',
  path: '/antigravity/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const QoderWorkspaceKeyRoute = QoderWorkspaceKeyRouteImport.update({
  id: '/qoder/$workspaceKey',
  path: '/qoder/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const QoderSessionsSessionIdRoute = QoderSessionsSessionIdRouteImport.update({
  id: '/qoder-sessions/$sessionId',
  path: '/qoder-sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencodeWorkspaceKeyRoute = OpencodeWorkspaceKeyRouteImport.update({
  id: '/opencode/$workspaceKey',
  path: '/opencode/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencodeSessionsSessionIdRoute =
  OpencodeSessionsSessionIdRouteImport.update({
    id: '/opencode-sessions/$sessionId',
    path: '/opencode-sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MinimaxCodeWorkspaceKeyRoute = MinimaxCodeWorkspaceKeyRouteImport.update({
  id: '/minimax-code/$workspaceKey',
  path: '/minimax-code/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimaxCodeSessionsSessionIdRoute =
  MinimaxCodeSessionsSessionIdRouteImport.update({
    id: '/minimax-code-sessions/$sessionId',
    path: '/minimax-code-sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const KiroWorkspaceKeyRoute = KiroWorkspaceKeyRouteImport.update({
  id: '/kiro/$workspaceKey',
  path: '/kiro/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const KiroSessionsSessionIdRoute = KiroSessionsSessionIdRouteImport.update({
  id: '/kiro-sessions/$sessionId',
  path: '/kiro-sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokWorkspaceKeyRoute = GrokWorkspaceKeyRouteImport.update({
  id: '/grok/$workspaceKey',
  path: '/grok/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokSessionsSessionIdRoute = GrokSessionsSessionIdRouteImport.update({
  id: '/grok-sessions/$sessionId',
  path: '/grok-sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorWorkspaceKeyRoute = CursorWorkspaceKeyRouteImport.update({
  id: '/cursor/$workspaceKey',
  path: '/cursor/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorThreadsComposerIdRoute = CursorThreadsComposerIdRouteImport.update({
  id: '/cursor-threads/$composerId',
  path: '/cursor-threads/$composerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexProjectRoute = CodexProjectRouteImport.update({
  id: '/codex/$project',
  path: '/codex/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeWorkspaceKeyRoute = ClaudeCodeWorkspaceKeyRouteImport.update({
  id: '/claude-code/$workspaceKey',
  path: '/claude-code/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeSessionsSessionIdRoute =
  ClaudeCodeSessionsSessionIdRouteImport.update({
    id: '/claude-code-sessions/$sessionId',
    path: '/claude-code-sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AntigravityWorkspaceKeyRoute = AntigravityWorkspaceKeyRouteImport.update({
  id: '/antigravity/$workspaceKey',
  path: '/antigravity/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigravityConversationsConversationIdRoute =
  AntigravityConversationsConversationIdRouteImport.update({
    id: '/antigravity-conversations/$conversationId',
    path: '/antigravity-conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SourcesRoute = ApiV1SourcesRouteImport.update({
  id: '/api/v1/sources',
  path: '/api/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ResolveRoute = ApiV1ResolveRouteImport.update({
  id: '/api/v1/resolve',
  path: '/api/v1/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConversationsRoute = ApiV1ConversationsRouteImport.update({
  id: '/api/v1/conversations',
  path: '/api/v1/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConversationQueryRoute = ApiV1ConversationQueryRouteImport.update({
  id: '/api/v1/conversation-query',
  path: '/api/v1/conversation-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConversationsExportRoute =
  ApiV1ConversationsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiV1ConversationsRoute,
  } as any)
const ApiV1ConversationsDeleteRoute =
  ApiV1ConversationsDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiV1ConversationsRoute,
  } as any)
const ApiV1ConversationsSourceIdRoute =
  ApiV1ConversationsSourceIdRouteImport.update({
    id: '/$source/$id',
    path: '/$source/$id',
    getParentRoute: () => ApiV1ConversationsRoute,
  } as any)
const ApiV1CodexThreadsEventsRoute = ApiV1CodexThreadsEventsRouteImport.update({
  id: '/api/v1/codex/threads/events',
  path: '/api/v1/codex/threads/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConversationsSourceIdExportRoute =
  ApiV1ConversationsSourceIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiV1ConversationsSourceIdRoute,
  } as any)
const ApiV1ConversationsSourceIdEvidenceRoute =
  ApiV1ConversationsSourceIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => ApiV1ConversationsSourceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/claude-code-sessions/$sessionId': typeof ClaudeCodeSessionsSessionIdRoute
  '/claude-code/$workspaceKey': typeof ClaudeCodeWorkspaceKeyRoute
  '/codex/$project': typeof CodexProjectRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/grok-sessions/$sessionId': typeof GrokSessionsSessionIdRoute
  '/grok/$workspaceKey': typeof GrokWorkspaceKeyRoute
  '/kiro-sessions/$sessionId': typeof KiroSessionsSessionIdRoute
  '/kiro/$workspaceKey': typeof KiroWorkspaceKeyRoute
  '/minimax-code-sessions/$sessionId': typeof MinimaxCodeSessionsSessionIdRoute
  '/minimax-code/$workspaceKey': typeof MinimaxCodeWorkspaceKeyRoute
  '/opencode-sessions/$sessionId': typeof OpencodeSessionsSessionIdRoute
  '/opencode/$workspaceKey': typeof OpencodeWorkspaceKeyRoute
  '/qoder-sessions/$sessionId': typeof QoderSessionsSessionIdRoute
  '/qoder/$workspaceKey': typeof QoderWorkspaceKeyRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity/': typeof AntigravityIndexRoute
  '/claude-code/': typeof ClaudeCodeIndexRoute
  '/codex/': typeof CodexIndexRoute
  '/cursor/': typeof CursorIndexRoute
  '/grok/': typeof GrokIndexRoute
  '/kiro/': typeof KiroIndexRoute
  '/minimax-code/': typeof MinimaxCodeIndexRoute
  '/opencode/': typeof OpencodeIndexRoute
  '/qoder/': typeof QoderIndexRoute
  '/api/v1/conversation-query': typeof ApiV1ConversationQueryRoute
  '/api/v1/conversations': typeof ApiV1ConversationsRouteWithChildren
  '/api/v1/resolve': typeof ApiV1ResolveRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/api/v1/conversations/delete': typeof ApiV1ConversationsDeleteRoute
  '/api/v1/conversations/export': typeof ApiV1ConversationsExportRoute
  '/api/v1/codex/threads/events': typeof ApiV1CodexThreadsEventsRoute
  '/api/v1/conversations/$source/$id': typeof ApiV1ConversationsSourceIdRouteWithChildren
  '/api/v1/conversations/$source/$id/evidence': typeof ApiV1ConversationsSourceIdEvidenceRoute
  '/api/v1/conversations/$source/$id/export': typeof ApiV1ConversationsSourceIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/claude-code-sessions/$sessionId': typeof ClaudeCodeSessionsSessionIdRoute
  '/claude-code/$workspaceKey': typeof ClaudeCodeWorkspaceKeyRoute
  '/codex/$project': typeof CodexProjectRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/grok-sessions/$sessionId': typeof GrokSessionsSessionIdRoute
  '/grok/$workspaceKey': typeof GrokWorkspaceKeyRoute
  '/kiro-sessions/$sessionId': typeof KiroSessionsSessionIdRoute
  '/kiro/$workspaceKey': typeof KiroWorkspaceKeyRoute
  '/minimax-code-sessions/$sessionId': typeof MinimaxCodeSessionsSessionIdRoute
  '/minimax-code/$workspaceKey': typeof MinimaxCodeWorkspaceKeyRoute
  '/opencode-sessions/$sessionId': typeof OpencodeSessionsSessionIdRoute
  '/opencode/$workspaceKey': typeof OpencodeWorkspaceKeyRoute
  '/qoder-sessions/$sessionId': typeof QoderSessionsSessionIdRoute
  '/qoder/$workspaceKey': typeof QoderWorkspaceKeyRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity': typeof AntigravityIndexRoute
  '/claude-code': typeof ClaudeCodeIndexRoute
  '/codex': typeof CodexIndexRoute
  '/cursor': typeof CursorIndexRoute
  '/grok': typeof GrokIndexRoute
  '/kiro': typeof KiroIndexRoute
  '/minimax-code': typeof MinimaxCodeIndexRoute
  '/opencode': typeof OpencodeIndexRoute
  '/qoder': typeof QoderIndexRoute
  '/api/v1/conversation-query': typeof ApiV1ConversationQueryRoute
  '/api/v1/conversations': typeof ApiV1ConversationsRouteWithChildren
  '/api/v1/resolve': typeof ApiV1ResolveRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/api/v1/conversations/delete': typeof ApiV1ConversationsDeleteRoute
  '/api/v1/conversations/export': typeof ApiV1ConversationsExportRoute
  '/api/v1/codex/threads/events': typeof ApiV1CodexThreadsEventsRoute
  '/api/v1/conversations/$source/$id': typeof ApiV1ConversationsSourceIdRouteWithChildren
  '/api/v1/conversations/$source/$id/evidence': typeof ApiV1ConversationsSourceIdEvidenceRoute
  '/api/v1/conversations/$source/$id/export': typeof ApiV1ConversationsSourceIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/antigravity-conversations/$conversationId': typeof AntigravityConversationsConversationIdRoute
  '/antigravity/$workspaceKey': typeof AntigravityWorkspaceKeyRoute
  '/claude-code-sessions/$sessionId': typeof ClaudeCodeSessionsSessionIdRoute
  '/claude-code/$workspaceKey': typeof ClaudeCodeWorkspaceKeyRoute
  '/codex/$project': typeof CodexProjectRoute
  '/cursor-threads/$composerId': typeof CursorThreadsComposerIdRoute
  '/cursor/$workspaceKey': typeof CursorWorkspaceKeyRoute
  '/grok-sessions/$sessionId': typeof GrokSessionsSessionIdRoute
  '/grok/$workspaceKey': typeof GrokWorkspaceKeyRoute
  '/kiro-sessions/$sessionId': typeof KiroSessionsSessionIdRoute
  '/kiro/$workspaceKey': typeof KiroWorkspaceKeyRoute
  '/minimax-code-sessions/$sessionId': typeof MinimaxCodeSessionsSessionIdRoute
  '/minimax-code/$workspaceKey': typeof MinimaxCodeWorkspaceKeyRoute
  '/opencode-sessions/$sessionId': typeof OpencodeSessionsSessionIdRoute
  '/opencode/$workspaceKey': typeof OpencodeWorkspaceKeyRoute
  '/qoder-sessions/$sessionId': typeof QoderSessionsSessionIdRoute
  '/qoder/$workspaceKey': typeof QoderWorkspaceKeyRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/antigravity/': typeof AntigravityIndexRoute
  '/claude-code/': typeof ClaudeCodeIndexRoute
  '/codex/': typeof CodexIndexRoute
  '/cursor/': typeof CursorIndexRoute
  '/grok/': typeof GrokIndexRoute
  '/kiro/': typeof KiroIndexRoute
  '/minimax-code/': typeof MinimaxCodeIndexRoute
  '/opencode/': typeof OpencodeIndexRoute
  '/qoder/': typeof QoderIndexRoute
  '/api/v1/conversation-query': typeof ApiV1ConversationQueryRoute
  '/api/v1/conversations': typeof ApiV1ConversationsRouteWithChildren
  '/api/v1/resolve': typeof ApiV1ResolveRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/api/v1/conversations/delete': typeof ApiV1ConversationsDeleteRoute
  '/api/v1/conversations/export': typeof ApiV1ConversationsExportRoute
  '/api/v1/codex/threads/events': typeof ApiV1CodexThreadsEventsRoute
  '/api/v1/conversations/$source/$id': typeof ApiV1ConversationsSourceIdRouteWithChildren
  '/api/v1/conversations/$source/$id/evidence': typeof ApiV1ConversationsSourceIdEvidenceRoute
  '/api/v1/conversations/$source/$id/export': typeof ApiV1ConversationsSourceIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/claude-code-sessions/$sessionId'
    | '/claude-code/$workspaceKey'
    | '/codex/$project'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/grok-sessions/$sessionId'
    | '/grok/$workspaceKey'
    | '/kiro-sessions/$sessionId'
    | '/kiro/$workspaceKey'
    | '/minimax-code-sessions/$sessionId'
    | '/minimax-code/$workspaceKey'
    | '/opencode-sessions/$sessionId'
    | '/opencode/$workspaceKey'
    | '/qoder-sessions/$sessionId'
    | '/qoder/$workspaceKey'
    | '/threads/$threadId'
    | '/antigravity/'
    | '/claude-code/'
    | '/codex/'
    | '/cursor/'
    | '/grok/'
    | '/kiro/'
    | '/minimax-code/'
    | '/opencode/'
    | '/qoder/'
    | '/api/v1/conversation-query'
    | '/api/v1/conversations'
    | '/api/v1/resolve'
    | '/api/v1/sources'
    | '/api/v1/conversations/delete'
    | '/api/v1/conversations/export'
    | '/api/v1/codex/threads/events'
    | '/api/v1/conversations/$source/$id'
    | '/api/v1/conversations/$source/$id/evidence'
    | '/api/v1/conversations/$source/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/claude-code-sessions/$sessionId'
    | '/claude-code/$workspaceKey'
    | '/codex/$project'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/grok-sessions/$sessionId'
    | '/grok/$workspaceKey'
    | '/kiro-sessions/$sessionId'
    | '/kiro/$workspaceKey'
    | '/minimax-code-sessions/$sessionId'
    | '/minimax-code/$workspaceKey'
    | '/opencode-sessions/$sessionId'
    | '/opencode/$workspaceKey'
    | '/qoder-sessions/$sessionId'
    | '/qoder/$workspaceKey'
    | '/threads/$threadId'
    | '/antigravity'
    | '/claude-code'
    | '/codex'
    | '/cursor'
    | '/grok'
    | '/kiro'
    | '/minimax-code'
    | '/opencode'
    | '/qoder'
    | '/api/v1/conversation-query'
    | '/api/v1/conversations'
    | '/api/v1/resolve'
    | '/api/v1/sources'
    | '/api/v1/conversations/delete'
    | '/api/v1/conversations/export'
    | '/api/v1/codex/threads/events'
    | '/api/v1/conversations/$source/$id'
    | '/api/v1/conversations/$source/$id/evidence'
    | '/api/v1/conversations/$source/$id/export'
  id:
    | '__root__'
    | '/'
    | '/$threadId'
    | '/analytics'
    | '/settings'
    | '/antigravity-conversations/$conversationId'
    | '/antigravity/$workspaceKey'
    | '/claude-code-sessions/$sessionId'
    | '/claude-code/$workspaceKey'
    | '/codex/$project'
    | '/cursor-threads/$composerId'
    | '/cursor/$workspaceKey'
    | '/grok-sessions/$sessionId'
    | '/grok/$workspaceKey'
    | '/kiro-sessions/$sessionId'
    | '/kiro/$workspaceKey'
    | '/minimax-code-sessions/$sessionId'
    | '/minimax-code/$workspaceKey'
    | '/opencode-sessions/$sessionId'
    | '/opencode/$workspaceKey'
    | '/qoder-sessions/$sessionId'
    | '/qoder/$workspaceKey'
    | '/threads/$threadId'
    | '/antigravity/'
    | '/claude-code/'
    | '/codex/'
    | '/cursor/'
    | '/grok/'
    | '/kiro/'
    | '/minimax-code/'
    | '/opencode/'
    | '/qoder/'
    | '/api/v1/conversation-query'
    | '/api/v1/conversations'
    | '/api/v1/resolve'
    | '/api/v1/sources'
    | '/api/v1/conversations/delete'
    | '/api/v1/conversations/export'
    | '/api/v1/codex/threads/events'
    | '/api/v1/conversations/$source/$id'
    | '/api/v1/conversations/$source/$id/evidence'
    | '/api/v1/conversations/$source/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  AnalyticsRoute: typeof AnalyticsRoute
  SettingsRoute: typeof SettingsRoute
  AntigravityConversationsConversationIdRoute: typeof AntigravityConversationsConversationIdRoute
  AntigravityWorkspaceKeyRoute: typeof AntigravityWorkspaceKeyRoute
  ClaudeCodeSessionsSessionIdRoute: typeof ClaudeCodeSessionsSessionIdRoute
  ClaudeCodeWorkspaceKeyRoute: typeof ClaudeCodeWorkspaceKeyRoute
  CodexProjectRoute: typeof CodexProjectRoute
  CursorThreadsComposerIdRoute: typeof CursorThreadsComposerIdRoute
  CursorWorkspaceKeyRoute: typeof CursorWorkspaceKeyRoute
  GrokSessionsSessionIdRoute: typeof GrokSessionsSessionIdRoute
  GrokWorkspaceKeyRoute: typeof GrokWorkspaceKeyRoute
  KiroSessionsSessionIdRoute: typeof KiroSessionsSessionIdRoute
  KiroWorkspaceKeyRoute: typeof KiroWorkspaceKeyRoute
  MinimaxCodeSessionsSessionIdRoute: typeof MinimaxCodeSessionsSessionIdRoute
  MinimaxCodeWorkspaceKeyRoute: typeof MinimaxCodeWorkspaceKeyRoute
  OpencodeSessionsSessionIdRoute: typeof OpencodeSessionsSessionIdRoute
  OpencodeWorkspaceKeyRoute: typeof OpencodeWorkspaceKeyRoute
  QoderSessionsSessionIdRoute: typeof QoderSessionsSessionIdRoute
  QoderWorkspaceKeyRoute: typeof QoderWorkspaceKeyRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  AntigravityIndexRoute: typeof AntigravityIndexRoute
  ClaudeCodeIndexRoute: typeof ClaudeCodeIndexRoute
  CodexIndexRoute: typeof CodexIndexRoute
  CursorIndexRoute: typeof CursorIndexRoute
  GrokIndexRoute: typeof GrokIndexRoute
  KiroIndexRoute: typeof KiroIndexRoute
  MinimaxCodeIndexRoute: typeof MinimaxCodeIndexRoute
  OpencodeIndexRoute: typeof OpencodeIndexRoute
  QoderIndexRoute: typeof QoderIndexRoute
  ApiV1ConversationQueryRoute: typeof ApiV1ConversationQueryRoute
  ApiV1ConversationsRoute: typeof ApiV1ConversationsRouteWithChildren
  ApiV1ResolveRoute: typeof ApiV1ResolveRoute
  ApiV1SourcesRoute: typeof ApiV1SourcesRoute
  ApiV1CodexThreadsEventsRoute: typeof ApiV1CodexThreadsEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qoder/': {
      id: '/qoder/'
      path: '/qoder'
      fullPath: '/qoder/'
      preLoaderRoute: typeof QoderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencode/': {
      id: '/opencode/'
      path: '/opencode'
      fullPath: '/opencode/'
      preLoaderRoute: typeof OpencodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimax-code/': {
      id: '/minimax-code/'
      path: '/minimax-code'
      fullPath: '/minimax-code/'
      preLoaderRoute: typeof MinimaxCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiro/': {
      id: '/kiro/'
      path: '/kiro'
      fullPath: '/kiro/'
      preLoaderRoute: typeof KiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok/': {
      id: '/grok/'
      path: '/grok'
      fullPath: '/grok/'
      preLoaderRoute: typeof GrokIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor/': {
      id: '/cursor/'
      path: '/cursor'
      fullPath: '/cursor/'
      preLoaderRoute: typeof CursorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/': {
      id: '/codex/'
      path: '/codex'
      fullPath: '/codex/'
      preLoaderRoute: typeof CodexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code/': {
      id: '/claude-code/'
      path: '/claude-code'
      fullPath: '/claude-code/'
      preLoaderRoute: typeof ClaudeCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity/': {
      id: '/antigravity/'
      path: '/antigravity'
      fullPath: '/antigravity/'
      preLoaderRoute: typeof AntigravityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qoder/$workspaceKey': {
      id: '/qoder/$workspaceKey'
      path: '/qoder/$workspaceKey'
      fullPath: '/qoder/$workspaceKey'
      preLoaderRoute: typeof QoderWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qoder-sessions/$sessionId': {
      id: '/qoder-sessions/$sessionId'
      path: '/qoder-sessions/$sessionId'
      fullPath: '/qoder-sessions/$sessionId'
      preLoaderRoute: typeof QoderSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencode/$workspaceKey': {
      id: '/opencode/$workspaceKey'
      path: '/opencode/$workspaceKey'
      fullPath: '/opencode/$workspaceKey'
      preLoaderRoute: typeof OpencodeWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencode-sessions/$sessionId': {
      id: '/opencode-sessions/$sessionId'
      path: '/opencode-sessions/$sessionId'
      fullPath: '/opencode-sessions/$sessionId'
      preLoaderRoute: typeof OpencodeSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimax-code/$workspaceKey': {
      id: '/minimax-code/$workspaceKey'
      path: '/minimax-code/$workspaceKey'
      fullPath: '/minimax-code/$workspaceKey'
      preLoaderRoute: typeof MinimaxCodeWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimax-code-sessions/$sessionId': {
      id: '/minimax-code-sessions/$sessionId'
      path: '/minimax-code-sessions/$sessionId'
      fullPath: '/minimax-code-sessions/$sessionId'
      preLoaderRoute: typeof MinimaxCodeSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiro/$workspaceKey': {
      id: '/kiro/$workspaceKey'
      path: '/kiro/$workspaceKey'
      fullPath: '/kiro/$workspaceKey'
      preLoaderRoute: typeof KiroWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiro-sessions/$sessionId': {
      id: '/kiro-sessions/$sessionId'
      path: '/kiro-sessions/$sessionId'
      fullPath: '/kiro-sessions/$sessionId'
      preLoaderRoute: typeof KiroSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok/$workspaceKey': {
      id: '/grok/$workspaceKey'
      path: '/grok/$workspaceKey'
      fullPath: '/grok/$workspaceKey'
      preLoaderRoute: typeof GrokWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok-sessions/$sessionId': {
      id: '/grok-sessions/$sessionId'
      path: '/grok-sessions/$sessionId'
      fullPath: '/grok-sessions/$sessionId'
      preLoaderRoute: typeof GrokSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor/$workspaceKey': {
      id: '/cursor/$workspaceKey'
      path: '/cursor/$workspaceKey'
      fullPath: '/cursor/$workspaceKey'
      preLoaderRoute: typeof CursorWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor-threads/$composerId': {
      id: '/cursor-threads/$composerId'
      path: '/cursor-threads/$composerId'
      fullPath: '/cursor-threads/$composerId'
      preLoaderRoute: typeof CursorThreadsComposerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/$project': {
      id: '/codex/$project'
      path: '/codex/$project'
      fullPath: '/codex/$project'
      preLoaderRoute: typeof CodexProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code/$workspaceKey': {
      id: '/claude-code/$workspaceKey'
      path: '/claude-code/$workspaceKey'
      fullPath: '/claude-code/$workspaceKey'
      preLoaderRoute: typeof ClaudeCodeWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code-sessions/$sessionId': {
      id: '/claude-code-sessions/$sessionId'
      path: '/claude-code-sessions/$sessionId'
      fullPath: '/claude-code-sessions/$sessionId'
      preLoaderRoute: typeof ClaudeCodeSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity/$workspaceKey': {
      id: '/antigravity/$workspaceKey'
      path: '/antigravity/$workspaceKey'
      fullPath: '/antigravity/$workspaceKey'
      preLoaderRoute: typeof AntigravityWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigravity-conversations/$conversationId': {
      id: '/antigravity-conversations/$conversationId'
      path: '/antigravity-conversations/$conversationId'
      fullPath: '/antigravity-conversations/$conversationId'
      preLoaderRoute: typeof AntigravityConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sources': {
      id: '/api/v1/sources'
      path: '/api/v1/sources'
      fullPath: '/api/v1/sources'
      preLoaderRoute: typeof ApiV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/resolve': {
      id: '/api/v1/resolve'
      path: '/api/v1/resolve'
      fullPath: '/api/v1/resolve'
      preLoaderRoute: typeof ApiV1ResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/conversations': {
      id: '/api/v1/conversations'
      path: '/api/v1/conversations'
      fullPath: '/api/v1/conversations'
      preLoaderRoute: typeof ApiV1ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/conversation-query': {
      id: '/api/v1/conversation-query'
      path: '/api/v1/conversation-query'
      fullPath: '/api/v1/conversation-query'
      preLoaderRoute: typeof ApiV1ConversationQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/conversations/export': {
      id: '/api/v1/conversations/export'
      path: '/export'
      fullPath: '/api/v1/conversations/export'
      preLoaderRoute: typeof ApiV1ConversationsExportRouteImport
      parentRoute: typeof ApiV1ConversationsRoute
    }
    '/api/v1/conversations/delete': {
      id: '/api/v1/conversations/delete'
      path: '/delete'
      fullPath: '/api/v1/conversations/delete'
      preLoaderRoute: typeof ApiV1ConversationsDeleteRouteImport
      parentRoute: typeof ApiV1ConversationsRoute
    }
    '/api/v1/conversations/$source/$id': {
      id: '/api/v1/conversations/$source/$id'
      path: '/$source/$id'
      fullPath: '/api/v1/conversations/$source/$id'
      preLoaderRoute: typeof ApiV1ConversationsSourceIdRouteImport
      parentRoute: typeof ApiV1ConversationsRoute
    }
    '/api/v1/codex/threads/events': {
      id: '/api/v1/codex/threads/events'
      path: '/api/v1/codex/threads/events'
      fullPath: '/api/v1/codex/threads/events'
      preLoaderRoute: typeof ApiV1CodexThreadsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/conversations/$source/$id/export': {
      id: '/api/v1/conversations/$source/$id/export'
      path: '/export'
      fullPath: '/api/v1/conversations/$source/$id/export'
      preLoaderRoute: typeof ApiV1ConversationsSourceIdExportRouteImport
      parentRoute: typeof ApiV1ConversationsSourceIdRoute
    }
    '/api/v1/conversations/$source/$id/evidence': {
      id: '/api/v1/conversations/$source/$id/evidence'
      path: '/evidence'
      fullPath: '/api/v1/conversations/$source/$id/evidence'
      preLoaderRoute: typeof ApiV1ConversationsSourceIdEvidenceRouteImport
      parentRoute: typeof ApiV1ConversationsSourceIdRoute
    }
  }
}

interface ApiV1ConversationsSourceIdRouteChildren {
  ApiV1ConversationsSourceIdEvidenceRoute: typeof ApiV1ConversationsSourceIdEvidenceRoute
  ApiV1ConversationsSourceIdExportRoute: typeof ApiV1ConversationsSourceIdExportRoute
}

const ApiV1ConversationsSourceIdRouteChildren: ApiV1ConversationsSourceIdRouteChildren =
  {
    ApiV1ConversationsSourceIdEvidenceRoute:
      ApiV1ConversationsSourceIdEvidenceRoute,
    ApiV1ConversationsSourceIdExportRoute:
      ApiV1ConversationsSourceIdExportRoute,
  }

const ApiV1ConversationsSourceIdRouteWithChildren =
  ApiV1ConversationsSourceIdRoute._addFileChildren(
    ApiV1ConversationsSourceIdRouteChildren,
  )

interface ApiV1ConversationsRouteChildren {
  ApiV1ConversationsDeleteRoute: typeof ApiV1ConversationsDeleteRoute
  ApiV1ConversationsExportRoute: typeof ApiV1ConversationsExportRoute
  ApiV1ConversationsSourceIdRoute: typeof ApiV1ConversationsSourceIdRouteWithChildren
}

const ApiV1ConversationsRouteChildren: ApiV1ConversationsRouteChildren = {
  ApiV1ConversationsDeleteRoute: ApiV1ConversationsDeleteRoute,
  ApiV1ConversationsExportRoute: ApiV1ConversationsExportRoute,
  ApiV1ConversationsSourceIdRoute: ApiV1ConversationsSourceIdRouteWithChildren,
}

const ApiV1ConversationsRouteWithChildren =
  ApiV1ConversationsRoute._addFileChildren(ApiV1ConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  AnalyticsRoute: AnalyticsRoute,
  SettingsRoute: SettingsRoute,
  AntigravityConversationsConversationIdRoute:
    AntigravityConversationsConversationIdRoute,
  AntigravityWorkspaceKeyRoute: AntigravityWorkspaceKeyRoute,
  ClaudeCodeSessionsSessionIdRoute: ClaudeCodeSessionsSessionIdRoute,
  ClaudeCodeWorkspaceKeyRoute: ClaudeCodeWorkspaceKeyRoute,
  CodexProjectRoute: CodexProjectRoute,
  CursorThreadsComposerIdRoute: CursorThreadsComposerIdRoute,
  CursorWorkspaceKeyRoute: CursorWorkspaceKeyRoute,
  GrokSessionsSessionIdRoute: GrokSessionsSessionIdRoute,
  GrokWorkspaceKeyRoute: GrokWorkspaceKeyRoute,
  KiroSessionsSessionIdRoute: KiroSessionsSessionIdRoute,
  KiroWorkspaceKeyRoute: KiroWorkspaceKeyRoute,
  MinimaxCodeSessionsSessionIdRoute: MinimaxCodeSessionsSessionIdRoute,
  MinimaxCodeWorkspaceKeyRoute: MinimaxCodeWorkspaceKeyRoute,
  OpencodeSessionsSessionIdRoute: OpencodeSessionsSessionIdRoute,
  OpencodeWorkspaceKeyRoute: OpencodeWorkspaceKeyRoute,
  QoderSessionsSessionIdRoute: QoderSessionsSessionIdRoute,
  QoderWorkspaceKeyRoute: QoderWorkspaceKeyRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  AntigravityIndexRoute: AntigravityIndexRoute,
  ClaudeCodeIndexRoute: ClaudeCodeIndexRoute,
  CodexIndexRoute: CodexIndexRoute,
  CursorIndexRoute: CursorIndexRoute,
  GrokIndexRoute: GrokIndexRoute,
  KiroIndexRoute: KiroIndexRoute,
  MinimaxCodeIndexRoute: MinimaxCodeIndexRoute,
  OpencodeIndexRoute: OpencodeIndexRoute,
  QoderIndexRoute: QoderIndexRoute,
  ApiV1ConversationQueryRoute: ApiV1ConversationQueryRoute,
  ApiV1ConversationsRoute: ApiV1ConversationsRouteWithChildren,
  ApiV1ResolveRoute: ApiV1ResolveRoute,
  ApiV1SourcesRoute: ApiV1SourcesRoute,
  ApiV1CodexThreadsEventsRoute: ApiV1CodexThreadsEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
